version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_Scrapy
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: